apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: tweets-subscription
  namespace: {{ .Release.Namespace }}
spec:
  topic: tweets
  route: /tweets
  pubsubname: tweet-pubsub
scopes:
  - viewer