apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: {{ .Release.Namespace }}
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: {{ .Values.tracing.zipkin.endpointAddress }}