apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweets
spec:
  type: bindings.twitter
  version: v1
  metadata:
    # PLACE TWITTER CREDENTIALS HERE
  - name: consumerKey
    value: {{ .Values.twitter.consumerKey }}
  - name: consumerSecret
    value: {{ .Values.twitter.consumerSecret }}
  - name: accessToken
    value: {{ .Values.twitter.accessToken }}
  - name: accessSecret
    value: {{ .Values.twitter.accessSecret }}
  - name: query
    value: "microsoft"
