# Default values for demochart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
demoName: "twitterSentimentProcessor"

fullnameOverride: provider

dapr:
   port: 3500

replicaCount: 1
port: 3001
image: "darquewarrior/provider:1.0.0"

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
  path: /
#   hosts:
#     - chart-example.local
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
   