apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "processor.fullname" . }}
  labels:
    app: {{ template "processor.name" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ template "processor.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "processor.name" . }}
        release: {{ .Release.Name }}
        demo: {{ .Values.demoName }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ template "processor.name" . }}
        dapr.io/app-port: {{ .Values.port | quote }}
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: processor
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: PORT
          value: {{ .Values.port | quote }}
        - name: DAPR_HTTP_PORT
          value: {{ .Values.dapr.port | quote}}
        - name: CS_ENDPOINT
          value: {{ .Values.cognitiveService.endpoint | quote }}
        - name: CS_TOKEN
          valueFrom:
            secretKeyRef:
              name: demo-processor-secret
              key: token
