# Default values for demochart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
demoName: "twitterSentimentProcessor"

dapr:
   port: 3500

serviceBus:
   connectionString: ""

tableStorage:
   name: ""
   key: ""

twitter:
   consumerKey: ""
   consumerSecret: ""
   accessToken: ""
   accessSecret: ""
   