apiVersion: v1
kind: Service
metadata:
  name: viewer
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.viewer.externalPort }}
      targetPort: {{ .Values.viewer.port }}
      protocol: TCP
      name: http
  selector:
    app: viewer