name: Deploy Twitter Sentiment

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  RG_NAME: "twitterKubeCon"
  LOCATION: "eastus"
  DAPR_VERSION: "1.6.0"
  K8S_VERSION: "1.23.5"

jobs:
  deploy:
    name: deployTwitterSentinment
    runs-on: ubuntu-latest
    steps:
    - name: checkout main branch
      uses: actions/checkout@v2

    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Bicep
    - name: Deploy infrastructure
      id: azure-deployment
      shell: pwsh
      run: |
        $deployment = $(az deployment sub create --name ${{ env.RG_NAME }} `
          --location ${{ env.LOCATION }} `
          --template-file ./iac/main.bicep `
          --parameters location=${{ env.LOCATION }} `
          --parameters rgName=${{ env.RG_NAME }} `
          --parameters k8sversion=${{ env.K8S_VERSION }} `
          --output json) | ConvertFrom-Json
        # Get all the outputs
        Write-Output "::set-output name=aksName::$($deployment.properties.outputs.aksName.value)"
        Write-Output "::set-output name=storageAccountKey::$($deployment.properties.outputs.storageAccountKey.value)"
        Write-Output "::set-output name=serviceBusEndpoint::$($deployment.properties.outputs.serviceBusEndpoint.value)"
        Write-Output "::set-output name=storageAccountName::$($deployment.properties.outputs.storageAccountName.value)"
        Write-Output "::set-output name=cognitiveServiceKey::$($deployment.properties.outputs.cognitiveServiceKey.value)"
        Write-Output "::set-output name=cognitiveServiceEndpoint::$($deployment.properties.outputs.cognitiveServiceEndpoint.value)"
      working-directory: ./twitter-sentiment-processor/demos/demo3   
  
    - name: Install Dapr via AKS Extension
      run: |
        az extension add --name k8s-extension

        az k8s-extension create --cluster-type managedClusters \
          --cluster-name ${{ steps.azure-deployment.outputs.aksName }} \
          --resource-group ${{ env.RG_NAME }} \
          --name daprK8s\
          --extension-type Microsoft.Dapr \
          --auto-upgrade-minor-version false \
          --version ${{ env.DAPR_VERSION }} \
          --only-show-errors

    - name: Get Dev K8s Context
      uses: azure/aks-set-context@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
        cluster-name: ${{ steps.azure-deployment.outputs.aksName }}
        resource-group: ${{ env.RG_NAME }}
    
    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.8.2'
      id: install
    
    - name: Helm Install
      run: |
        CHARTDIR="./charts/"
        echo "---"
        echo "Chart directory: $CHARTDIR"
        
        helm dependency update "$CHARTDIR"

        helm upgrade \
          --install twitter-kubecon "$CHARTDIR" \
          --namespace twitter-kubecon --create-namespace \
          --set components.serviceBus.connectionString="${{ steps.azure-deployment.outputs.serviceBusEndpoint }}" \
          --set processor.cognitiveService.token=${{ steps.azure-deployment.outputs.cognitiveServiceKey }} \
          --set processor.cognitiveService.endpoint="${{ steps.azure-deployment.outputs.cognitiveServiceEndpoint }}" \
          --set components.tableStorage.key="${{ steps.azure-deployment.outputs.storageAccountKey }}" \
          --set components.tableStorage.name="${{ steps.azure-deployment.outputs.storageAccountName }}" \
          --set components.twitter.consumerKey=${{ secrets.TWITTER_CONSUMERKEY }} \
          --set components.twitter.consumerSecret=${{ secrets.TWITTER_CONSUMERSECRET }} \
          --set components.twitter.accessToken=${{ secrets.TWITTER_ACCESSTOKEN }} \
          --set components.twitter.accessSecret=${{ secrets.TWITTER_ACCESSSECRET }}
      working-directory: ./twitter-sentiment-processor/demos/demo3
