name: PRFlow Twitter Sentiment

on:
  pull_request:
    branches:
      - main
    paths:
      - twitter-sentiment-processor/demos/demo2/**
  workflow_dispatch:

env:
  # The name of the resource group to be created. All resources will be place
  # in the resource group and start with name.
  RG_NAME: "twitterDemo"

  # The location to store the meta data for the deployment.
  LOCATION: "eastus"

  #The version of the dapr runtime version to deploy.
  DAPR_VERSION: "1.3.0"

  # The version of k8s control plane.
  K8S_VERSION: "1.21.2"
  
jobs:
  buildImage:
    name: build provider image
    runs-on: ubuntu-latest
    steps:
    # checkout branch
    - name: checkout main branch
      uses: actions/checkout@v2

    # log into Azure
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Bicep
    - name: Deploy infrastructure
      id: azure-deployment
      shell: pwsh
      run: |
        $deployment = $(az deployment sub create --name ${{ env.RG_NAME }} `
          --location ${{ env.LOCATION }} `
          --template-file ./iac/main.bicep `
          --parameters location=${{ env.LOCATION }} `
          --parameters rgName=${{ env.RG_NAME }} `
          --parameters k8sversion=${{ env.K8S_VERSION }} `
          --output json) | ConvertFrom-Json
        # Get all the outputs
        Write-Output "::set-output name=aksName::$($deployment.properties.outputs.aksName.value)"
        Write-Output "::set-output name=storageAccountKey::$($deployment.properties.outputs.storageAccountKey.value)"
        Write-Output "::set-output name=serviceBusEndpoint::$($deployment.properties.outputs.serviceBusEndpoint.value)"
        Write-Output "::set-output name=storageAccountName::$($deployment.properties.outputs.storageAccountName.value)"
        Write-Output "::set-output name=cognitiveServiceKey::$($deployment.properties.outputs.cognitiveServiceKey.value)"
        Write-Output "::set-output name=cognitiveServiceEndpoint::$($deployment.properties.outputs.cognitiveServiceEndpoint.value)"
      working-directory: ./twitter-sentiment-processor/demos/demo3

    # Setup Dapr
    - name: Install Dapr
      uses: dapr/setup-dapr@v1

    # dapr init
    - name: Initialize Dapr
      shell: pwsh
      run: |
        Write-Host "${{ steps.azure-deployment.outputs.aksName }}"
        # Get the credentials to use with dapr init and helm install
        az aks get-credentials --resource-group ${{ env.RG_NAME }} --name "${{ steps.azure-deployment.outputs.aksName }}"
        # Initialize Dapr
        # Dapr init is very noisy in the logs so group these lines so
        # it can be collapsed.
        Write-Output "::group::Initialize Dapr"
        dapr init --kubernetes --wait --runtime-version ${{ env.DAPR_VERSION }}
        Write-Output "::endgroup::"
        dapr status --kubernetes
      working-directory: ./twitter-sentiment-processor/demos/demo3
    
    - name: "docker login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY }}/provider:${{ github.run_number }}
        context: ./twitter-sentiment-processor/demos/demo2/provider/
    
    - name: Get Dev K8s Context
      uses: azure/aks-set-context@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
        cluster-name: ${{ steps.azure-deployment.outputs.aksName }}
        resource-group: ${{ env.RG_NAME }}
    
    - name: Create valid namespace name
      id: generate-valid-namespace-name
      run: |
        namespaceName=${GITHUB_HEAD_REF::63}        
        namespaceName=$(echo ${namespaceName//[!0-9a-zA-Z]/-} | tr '[:upper:]' '[:lower:]' | sed -e 's/^-/z/' -e 's/-$/z/')
        echo ::set-output name=result::$namespaceName
    
    - name: Helm Install PR
      run: |
        CHARTDIR="./charts/"
        echo "---"
        echo "Chart directory: $CHARTDIR"
        
        echo "---"
        echo "Working Directory is: $PWD"
        
        helm dependency update "$CHARTDIR"

        helm upgrade --install ${{steps.generate-valid-namespace-name.outputs.result}} "$CHARTDIR" \
          --namespace ${{steps.generate-valid-namespace-name.outputs.result}} --create-namespace \
          --set provider.image=${{ secrets.CONTAINER_REGISTRY }}/provider:${{ github.run_number }} \
          --set viewer.ingress.hosts=${{steps.generate-valid-namespace-name.outputs.result}}.viewer.${{ secrets.HOST }} \
          --set zipkin.ingress.hosts=${{steps.generate-valid-namespace-name.outputs.result}}.zipkin.${{ secrets.HOST }} \
          --set fullnameOverride=${{steps.generate-valid-namespace-name.outputs.result}} \
          --set components.serviceBus.connectionString=${{ steps.azure-deployment.outputs.serviceBusEndpoint }} \
          --set processor.cognitiveService.token=${{ steps.azure-deployment.outputs.cognitiveServiceKey }} \
          --set processor.cognitiveService.endpoint=${{ steps.azure-deployment.outputs.cognitiveServiceEndpoint }} \
          --set components.tableStorage.key=${{ steps.azure-deployment.outputs.storageAccountKey }} \
          --set components.tableStorage.name=${{ steps.azure-deployment.outputs.storageAccountName }}
      working-directory: ./twitter-sentiment-processor/demos/demo3

    - uses: jldeen/dev-spaces/actions/add-review-url@Releases/v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        host: "${{ secrets.HOST }}"
        branch-name: ${{steps.generate-valid-namespace-name.outputs.result}}
        protocol: "http"